apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: repo-1020810059
  namespace: argocd
spec:
  encryptedData:
    project: AgABuUazlq3U+fmARFBS/kP8UIRuBBGm2KLW1zA/6F3i3sQfhumCoy9BmFTQKkoQVpVq7Wc98/e0IylbiiGOCr9tQleI9j5sUQwhWa1KSpy8uhtx85q+b7gXOmnFX1igMRLSZNKkTFpF9/1V9MyApxcyVmnn1rW1Ad9wJurOQObeU2xhYrtEjlwm5MTvcYBHEdPArxyHbs041wezPnCwMK465fdUP74K+OH5dyjcFdmS9LrU8tI8aTOm/Qg8LWPVipzWWfR53wMimJDfrrO9G1ldtjUnHB6CKWDyiP34IZXBJtbvpzIUL3bKRrQGnc2arM3VYonNxW46Cs/fFzImgP1k7W457RqimWLmKoI5v28YqXWGqoIRPsj6QtThQdwhm3D6T1Uhxfj65SCKI6vB1OHCb20dmXXn3vm8kHGRWpelNgLAOP5zX4Yv+WO5bHmcQosKoL0HE6Q/PEMr6hxENy2du5gAdIZh5tR/9IxWbG3YzNRy5eIXnvueFsbh8ujauKE7kVf5P8e1L5z8KFKTscUSTELMEXdxZHSAl1WRl+ki2SsY2i/S7361ImddLEK4fbuvuSUZyac7xoQz3aqx9gwJo0C4aw3EUzcH56E7Zz4swRabbn/3bCvs2KpSEdnHUNiflx2KpVNvRi55Px7/y5rswztoAGZ3quWJipaff8YSv73Vj9j6TPMO+VlTHFLgH+M2SNJ6nBKr
    type: AgCAtwkW9D2ATr0IAgFSNRWfo1wOBda+pzVBAzsZFYztYt0eFZGbHmmypYUfEh4G/DXkDrbZZAwiYdqA1ZDi+0yJg8BFNNy+1+3aTtjybcJhSsghlOFEKSWov8ASS8Ne9szkd8ZU7V2VM10LjQOuNoUCe+UBY4vUxOlxGML/PkY423nNtSrZRy6zmqr9tYCqmfIeRrsEs84qpZT6z9WMUyfPNtk2fGZVj3veHZ/X2kJcwDTNzbIAjEOk5bLLThfHht13KkU5iFSWz/lgq4HRoQRr6wLipj7FNx6u8htIK7mnAifJIBoDTptqTQDbBoSkeiD+KL8GYUgBgaN5PkLCSX/zz6xER+H7fyKRsyhaBk4QlPqXLggnMtMcF/scRVumO28u/8bhwit7eviEt46xQzyVw17JB3Znl6xv51aEl1Ezz6Te8SaRskwBxbVHMhDNCNoQAcVZpFkRTFGG26C14LMRyp7Ka1Ojv3vXy4TpREAcxLA/EYvUY/ncR3q0niVX4ou9J2ZAkimUK51M0Ng2qKLWSPzbH/C4DLNrAsXo3Sj4tFuRoa4xmleQpQBMiXgd86OcJNUOjSuWW2vUCtipL/sJnU7VLpG5yivtswFSC04+hLcjvbO7FXEnUKSBGV7NTbKeTBRnySStWL/bJixNw9iOLTSwIzGch55GvCdPDEgWD1rstyx9XMNIGfR0qoJAgFZVf2U=
    url: AgBAD2JOX2/QW+kF3dFYcHniCEy11uf8vvTD3Pupy8NsQc1zW5beS+r6UtkBomoFQSKsFWeivsUv2fpUF/NDfgdm7qsECV+3jNRKcFwiJexwOZmTSqFz8NbqvL0T2tVlhCxktTTYrWk5HqwZBDz1NEiRgvWayO+YYAJqcqzPtL3YVQtmYQOeP1b/loMTnrjqX71mZiwwxjJN9s5nkPtpn4urETw/1+VGio8sJLBBYxCdlD28uTn7xyT+QTFFJgT1gP72MCv8D486dYWhE/exBaAZTZjewF+rkf4EGlBu7H/Ii95TQKzNAkFJL/bh+f8/+EY4yAtPv/3+3QbLLwX2YceH3TgzfB+TDni39qT9e+C8bOaPl3nzDCDuVqBBq+ezy5p2R1GRP58k4d4Dpc9q+sUGyKYrYCGw+XhRsVDYfF2GqGVGSw1AA5YdvE9T5lug7aYuTCL2inghFOGPQfMQ3KmaR76gq7LulHUAhK/FW4vAxNq8VX5nhFC3itFJOLJGlosBB1dKkAsGEGRUqvhr10apBkKD/FUDqq92ai7HixuNlmgQAu5RL8nc+UHehpvfuAwQvxSCNr3yys6D82k0bl7vwFpT37/Pg7EEi2dSJ0xUVeKsJ0w8enHzroBWwssfYSPWjtpD2FJ4WvX8OxDB/s0Pt6uzGk/c/3em24EAVGTHctG2KwPLsdrF0bCPSB1Vgwc1aOdlMKQB9eZc+4igo0PvYi/e7y/N6tUy++YLjjcgjzOCaBmEEVg9ugndjaY=
  template:
    metadata:
      annotations:
        managed-by: argocd.argoproj.io
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: repo-1020810059
      namespace: argocd
    type: Opaque

